import { useMemo } from 'react';

import type { ProductItem } from '@asb/shared';

import { useAppStore } from '../lib/store';
import { t } from '../lib/translations';
import RecommendationCard from './RecommendationCard';

/**
 * Renders 3 cards when store.solution is set. Returns null otherwise (so the
 * section disappears on new queries — no stale content flash).
 */
export default function RecommendationGrid({ products }: { products: ProductItem[] }) {
  const lang = useAppStore((s) => s.lang);
  const brand = useAppStore((s) => s.brand);
  const solution = useAppStore((s) => s.solution);
  const ui = t(lang);

  const picks = useMemo(() => {
    if (!solution) return [] as Array<{ product: ProductItem; rationale: string }>;
    const byId = new Map(products.map((p) => [p.id, p]));
    return solution.selectedProducts
      .map((id) => {
        const product = byId.get(id);
        if (!product) return null;
        return { product, rationale: solution.rationale[id] ?? '' };
      })
      .filter((x): x is { product: ProductItem; rationale: string } => x !== null);
  }, [solution, products]);

  if (!solution || picks.length === 0) return null;

  // Show "Generated by <model> · 1.2s" subtitle when server returns the meta.
  // Older deployments / cache hits without the field stay silent (?? short-circuit).
  // model is the source-of-truth string (the actual API call's `model` parameter)
  // — surfaced verbatim so users can verify "the chain didn't silently fall through".
  const meta =
    solution.model && typeof solution.latencyMs === 'number'
      ? ui.recommendationsBy(solution.model, (solution.latencyMs / 1000).toFixed(1))
      : solution.model
        ? `${solution.model}`
        : null;

  return (
    <section className="mt-10">
      <div className="mb-3 flex items-baseline justify-between gap-3">
        <h2 className="text-sm font-medium text-white/70">{ui.recommendationsTitle}</h2>
        {meta && (
          <span className="text-[11px] text-white/40 tabular-nums" title={solution.provider}>
            {meta}
          </span>
        )}
      </div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {picks.map(({ product, rationale }, i) => (
          <RecommendationCard
            key={product.id}
            product={product}
            rationale={rationale}
            lang={lang}
            brand={brand}
            rank={i}
          />
        ))}
      </div>
    </section>
  );
}
